# Configs
author = 'pietro.butti'
title = '2pts fits'

# Meson list
[ensemble]
    list = ['MediumCoarse','Coarse-1','Coarse-Phys','Fine-1']

[meson]
    list = ['D','Dst','Ds', 'Dsst']

[momenta]
    list = ['000','100','200','300','400','110','211','222']


[data]
    mdata = '/Users/pietro/code/software/B2heavy/b2heavy/FnalHISQMetadata.py'

    [data.MediumCoarse]
        name     = 'MediumCoarse'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 13
        mom_list = ['000','100','200','300','400','110','211','222']
        Nt       = 48

    [data.Coarse-1]
        name     = 'Coarse-1'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 11
        mom_list = ['000','100','200','300','110','211']
        Nt       = 64

    [data.Coarse-2]
        name     = 'Coarse-2'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 16
        mom_list = ['000','100','200','300','110','211']
        Nt       = 64
    
    [data.Coarse-Phys]
        name     = 'Coarse-Phys'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 19
        mom_list = ['000','100','200','300','110','211']
        Nt       = 64
    
    [data.Fine-1]
        name     = 'Fine-1'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 16
        mom_list = ['000','100','200','300','110','211']
        Nt       = 96
    

# binSizes  = {'MediumCoarse':13,
#              'Coarse-2':    16,
#              'Coarse-1':    11,
#              'Coarse-Phys': 19,
#              'Fine-1':      16,
#              'Fine-Phys':   16,
#              'SuperFine':   22}#22}


    
[fit]
    [fit.MediumCoarse]    
        [fit.MediumCoarse.Dst]
            smlist = ['d-d','1S-1S','d-1S']
            [fit.MediumCoarse.Dst.mom]
                [fit.MediumCoarse.Dst.mom.000]
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_000'
                    trange_eff = [13,19]
                    trange     = [4,20]
                [fit.MediumCoarse.Dst.mom.100] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_100'
                    trange_eff = [13,19]
                    trange     = [4,19]
                [fit.MediumCoarse.Dst.mom.200] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_200'
                    trange_eff = [13,19]
                    trange     = [4,18]
                [fit.MediumCoarse.Dst.mom.300] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_300'
                    trange_eff = [13,19]
                    trange     = [4,17]
                [fit.MediumCoarse.Dst.mom.400] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_400'
                    trange_eff = [13,19]
                    trange     = [4,13]
                [fit.MediumCoarse.Dst.mom.110] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_110'
                    trange_eff = [12,19]
                    trange     = [4,19]
                [fit.MediumCoarse.Dst.mom.211] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_211'
                    trange_eff = [10,17]
                    trange     = [4,18]
                [fit.MediumCoarse.Dst.mom.222] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_222'
                    trange_eff = [13,19]
                    trange     = [4,15]

    [fit.Coarse-2]
        [fit.Coarse-2.Dst]
            smlist  = ['d-d','1S-1S','d-1S']
            [fit.Coarse-2.Dst.mom.000]
                tag        = 'Coarse-2_Dst_000'
                nstates    = 3
                trange_eff = [12,25] 
                trange     = [9,17] 
            [fit.Coarse-2.Dst.mom.100]
                tag    = 'Coarse-2_Dst_100'
                nstates    = 3
                trange_eff = [12,23]
                trange     = [9,17] 
            [fit.Coarse-2.Dst.mom.200]
                tag        = 'Coarse-2_Dst_200'
                nstates    = 3
                trange_eff = [12,18]
                trange     = [9,17]
            [fit.Coarse-2.Dst.mom.300]
                tag        = 'Coarse-2_Dst_300'
                nstates    = 3
                trange_eff = [8,15] 
                trange     = [9,17]
            [fit.Coarse-2.Dst.mom.110]
                tag        = 'Coarse-2_Dst_110'
                nstates    = 3
                trange_eff = [13,25] 
                trange     = [9,17]
            [fit.Coarse-2.Dst.mom.211]
                tag        = 'Coarse-2_Dst_211'
                nstates    = 3
                trange_eff = [9,17]
                trange     = [9,17]

    [fit.Coarse-1]
        [fit.Coarse-1.Dst]
            smlist  = ['d-d','1S-1S','d-1S']
            [fit.Coarse-1.Dst.mom.000]
                tag        = 'Coarse-1_Dst_000'
                nstates    = 2
                trange_eff = [13,20] # 0.008    0.20 0.12
                # trange     = [5,26]  # [12,17] tmax=26
                trange     = [9,17]  # [12,17] tmax=26
            [fit.Coarse-1.Dst.mom.100]
                tag    = 'Coarse-1_Dst_100'
                nstates    = 2
                trange_eff = [13,20] # 0.025    0.2 0.8
                # trange     = [5,23] # [12,15] tmax=23
                trange     = [9,17] # [12,15] tmax=23
            [fit.Coarse-1.Dst.mom.200]
                tag        = 'Coarse-1_Dst_200'
                nstates    = 2
                trange_eff = [13,20] # 0.047      0.34 0.56
                # trange     = [5,21] # [8,20]
                trange     = [9,17] # [8,20]
            [fit.Coarse-1.Dst.mom.300]
                tag        = 'Coarse-1_Dst_300'
                nstates    = 2
                trange_eff = [10,17] # 0.04         0.37 0.09
                # trange     = [5,17] # [10,13]
                trange     = [9,17] # [10,13]
            [fit.Coarse-1.Dst.mom.110]
                tag        = 'Coarse-1_Dst_110'
                nstates    = 2
                trange_eff = [11,19] # 0.01         0.19 0.65
                # trange     = [5,23] #[10,17]
                trange     = [9,17] #[10,17]
            [fit.Coarse-1.Dst.mom.211]
                tag        = 'Coarse-1_Dst_211'
                nstates    = 2
                trange_eff = [11,19] # 0.01         0.32  0.3
                # trange     = [5,19]
                trange     = [9,17]
    [fit.Coarse-Phys]
        [fit.Coarse-Phys.Dst]
            smlist  = ['d-d','1S-1S','d-1S']
            [fit.Coarse-Phys.Dst.mom.000]
                tag        = 'Coarse-Phys_Dst_000'
                nstates    = 2
                trange_eff = [15,24] 
                # trange     = [5,25]
                trange     = [9,19]
            [fit.Coarse-Phys.Dst.mom.100]
                tag        = 'Coarse-Phys_Dst_100'
                nstates    = 2
                trange_eff = [15,22]
                # trange     = [5,22]
                trange     = [9,19] 
            [fit.Coarse-Phys.Dst.mom.200]
                tag        = 'Coarse-Phys_Dst_200'
                nstates    = 2
                trange_eff = [14,21]
                # trange     = [5,21]
                trange     = [9,19]
            [fit.Coarse-Phys.Dst.mom.300]
                tag        = 'Coarse-Phys_Dst_300'
                nstates    = 2
                trange_eff = [13,19] 
                # trange     = [5,19]
                trange     = [9,19] 
            [fit.Coarse-Phys.Dst.mom.110]
                tag        = 'Coarse-Phys_Dst_110'
                nstates    = 2
                trange_eff = [15,23] 
                # trange     = [5,23]
                trange     = [9,19] 
            [fit.Coarse-Phys.Dst.mom.211]
                tag        = 'Coarse-Phys_Dst_211'
                nstates    = 2
                trange_eff = [14,20] 
                # trange     = [5,20]
                trange     = [9,19]
    [fit.Fine-1]
        [fit.Fine-1.Dst]
            smlist  = ['d-d','1S-1S','d-1S']
            [fit.Fine-1.Dst.mom.000]
                tag        = 'Fine-1_Dst_000'
                nstates    = 2
                trange_eff = [16,28]
                # trange     = [7,25]
                trange     = [12,17]
            [fit.Fine-1.Dst.mom.100]
                tag        = 'Fine-1_Dst_100'
                nstates    = 2
                trange_eff = [16,31]
                # trange     = [7,25]
                trange     = [12,17]
            [fit.Fine-1.Dst.mom.200]
                tag        = 'Fine-1_Dst_200'
                nstates    = 2
                trange_eff = [15,31]
                # trange     = [7,25]
                trange     = [12,17]
            [fit.Fine-1.Dst.mom.300]
                tag        = 'Fine-1_Dst_300'
                nstates    = 2
                trange_eff = [15,25]
                # trange     = [7,25]
                trange     = [12,17]
            [fit.Fine-1.Dst.mom.110]
                tag        = 'Fine-1_Dst_110'
                nstates    = 2
                trange_eff = [16,35]
                # trange     = [7,25] 
                trange     = [12,17] 
            [fit.Fine-1.Dst.mom.211]
                tag        = 'Fine-1_Dst_211'
                nstates    = 2
                trange_eff = [16,29]
                # trange     = [7,25]
                trange     = [12,17]
