# Configs
author = 'pietro.butti'
title = '2pts fits'

# Meson list
[ensemble]
    list = ['MediumCoarse','Coarse-1']

[meson]
    list = ['D','Dst','Ds', 'Dsst']

[momenta]
    list = ['000','100','200','300','400','110','211','222']


[data]
    mdata = '/Users/pietro/code/software/B2heavy/b2heavy/FnalHISQMetadata.py'

    [data.MediumCoarse]
        name     = 'MediumCoarse'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 13
        mom_list = ['000','100','200','300','400','110','211','222']
        Nt       = 48

    [data.Coarse-1]
        name     = 'Coarse-1'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 11
        mom_list = ['000','100','200','300','110','211']
        Nt       = 64

    
[fit]
    [fit.MediumCoarse]    
        [fit.MediumCoarse.Dst]
            smlist = ['d-d','1S-1S','d-1S']
            [fit.MediumCoarse.Dst.mom]
                [fit.MediumCoarse.Dst.mom.000]
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_000'
                    trange_eff = [13,19]
                    trange     = [4,20]
                [fit.MediumCoarse.Dst.mom.100] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_100'
                    trange_eff = [13,19]
                    trange     = [4,19]
                [fit.MediumCoarse.Dst.mom.200] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_200'
                    trange_eff = [13,19]
                    trange     = [4,18]
                [fit.MediumCoarse.Dst.mom.300] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_300'
                    trange_eff = [13,19]
                    trange     = [4,17]
                [fit.MediumCoarse.Dst.mom.400] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_400'
                    trange_eff = [13,19]
                    trange     = [4,13]
                [fit.MediumCoarse.Dst.mom.110] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_110'
                    trange_eff = [12,19]
                    trange     = [4,19]
                [fit.MediumCoarse.Dst.mom.211] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_211'
                    trange_eff = [10,17]
                    trange     = [4,18]
                [fit.MediumCoarse.Dst.mom.222] 
                    nstates    = 3
                    tag        = 'MediumCoarse_Dst_222'
                    trange_eff = [13,19]
                    trange     = [4,15]


    [fit.Coarse-1]
        [fit.Coarse-1.Dst]
            smlist  = ['d-d','1S-1S','d-1S']
            [fit.Coarse-1.Dst.mom.000]
                tag        = 'Coarse-1_Dst_000'
                nstates    = 3
                trange_eff = [13,20] # 0.008    0.20 0.12
                trange     = [5,26]  # [12,17] tmax=26
            [fit.Coarse-1.Dst.mom.100]
                tag    = 'Coarse-1_Dst_100'
                nstates    = 3
                trange_eff = [13,20] # 0.025    0.2 0.8
                trange     = [5,23] # [12,15] tmax=23
            [fit.Coarse-1.Dst.mom.200]
                tag        = 'Coarse-1_Dst_200'
                nstates    = 3
                trange_eff = [13,20] # 0.047      0.34 0.56
                trange     = [5,21] # [8,20]
            [fit.Coarse-1.Dst.mom.300]
                tag        = 'Coarse-1_Dst_300'
                nstates    = 3
                trange_eff = [10,17] # 0.04         0.37 0.09
                trange     = [5,17] # [10,13]
            [fit.Coarse-1.Dst.mom.110]
                tag        = 'Coarse-1_Dst_110'
                nstates    = 3
                trange_eff = [11,19] # 0.01         0.19 0.65
                trange     = [5,23] #[10,17]
            [fit.Coarse-1.Dst.mom.211]
                tag        = 'Coarse-1_Dst_211'
                nstates    = 3
                trange_eff = [11,19] # 0.01         0.32  0.3
                trange     = [5,19]

 