# Configs
author = 'pietro.butti'
title = '3pts fits'

# Meson list
[ensemble]
    list = ['Coarse-1','Fine-1']

[ratio]
    list = ['xfstpar', 'XV', 'RA1', 'R0', 'R1']#,'ZRA1']

[momenta]
    list = ['000','100','200','300','400','110','211','222']


[data]
    mdata = '/Users/pietro/code/software/B2heavy/b2heavy/FnalHISQMetadata.py'

    [data.MediumCoarse]
        name     = 'MediumCoarse'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 13
        mom_list = ['000','100','200','300','400','110','211','222']
        Nt       = 48

    [data.Coarse-1]
        name     = 'Coarse-1'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 11
        mom_list = ['000','100','200','300','110','211']
        Nt       = 64
    
    [data.Coarse-Phys]
        name     = 'Coarse-Phys'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 19
        mom_list = ['000','100','200','300','110','211']
        Nt       = 64
    
    [data.Fine-1]
        name     = 'Fine-1'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 16
        mom_list = ['000','100','200','300','110','211']
        Nt       = 96
    

# binSizes  = {'MediumCoarse':13,
#              'Coarse-2':    16,
#              'Coarse-1':    11,
#              'Coarse-Phys': 19,
#              'Fine-1':      16,
#              'Fine-Phys':   16,
#              'SuperFine':   22}#22}


    
[fit]
    [fit.Coarse-1]
        [fit.Coarse-1.xfstpar]
            smlist = ['1S']
            [fit.Coarse-1.xfstpar.mom]
                [fit.Coarse-1.xfstpar.mom.100]
                    nstates = 2
                    tag     = 'Coarse-1_xfstpar_100'
                    trange  = [3,11]
                [fit.Coarse-1.xfstpar.mom.200]
                    nstates = 2
                    tag     = 'Coarse-1_xfstpar_200'
                    trange  = [3,11]            
                [fit.Coarse-1.xfstpar.mom.300]
                    nstates = 2
                    tag     = 'Coarse-1_xfstpar_300'
                    trange  = [3,11]

        [fit.Coarse-1.RA1]
            smlist = ['1S']
            [fit.Coarse-1.RA1.mom]
                [fit.Coarse-1.RA1.mom.000]
                    nstates = 2
                    tag     = 'Coarse-1_RA1_000'
                    trange  = [3,11]
                [fit.Coarse-1.RA1.mom.100]
                    nstates = 2
                    tag     = 'Coarse-1_RA1_100'
                    trange  = [3,11]
                [fit.Coarse-1.RA1.mom.200]
                    nstates = 2
                    tag     = 'Coarse-1_RA1_200'
                    trange  = [3,11]            
                [fit.Coarse-1.RA1.mom.300]
                    nstates = 2
                    tag     = 'Coarse-1_RA1_300'
                    trange  = [3,11]

        [fit.Coarse-1.ZRA1]
            smlist = ['1S']
            [fit.Coarse-1.ZRA1.mom]
                [fit.Coarse-1.ZRA1.mom.000]
                    nstates = 2
                    tag     = 'Coarse-1_ZRA1_000'
                    trange  = [3,11]

        [fit.Coarse-1.R0]
            smlist = ['1S']
            [fit.Coarse-1.R0.mom]
                [fit.Coarse-1.R0.mom.100]
                    nstates = 2
                    tag     = 'Coarse-1_R0_100'
                    trange  = [3,11]
                [fit.Coarse-1.R0.mom.200]
                    nstates = 2
                    tag     = 'Coarse-1_R0_200'
                    trange  = [3,11]            
                [fit.Coarse-1.R0.mom.300]
                    nstates = 2
                    tag     = 'Coarse-1_R0_300'
                    trange  = [3,11]

        [fit.Coarse-1.R1]
            smlist = ['1S']
            [fit.Coarse-1.R1.mom]
                [fit.Coarse-1.R1.mom.100]
                    nstates = 2
                    tag     = 'Coarse-1_R1_100'
                    trange  = [3,11]
                [fit.Coarse-1.R1.mom.200]
                    nstates = 2
                    tag     = 'Coarse-1_R1_200'
                    trange  = [3,11]            
                [fit.Coarse-1.R1.mom.300]
                    nstates = 2
                    tag     = 'Coarse-1_R1_300'
                    trange  = [3,11]

        [fit.Coarse-1.XV]
            smlist = ['1S']
            [fit.Coarse-1.XV.mom]
                [fit.Coarse-1.XV.mom.100]
                    nstates = 2
                    tag     = 'Coarse-1_XV_100'
                    trange  = [3,11]
                [fit.Coarse-1.XV.mom.200]
                    nstates = 2
                    tag     = 'Coarse-1_XV_200'
                    trange  = [3,11]            
                [fit.Coarse-1.XV.mom.300]
                    nstates = 2
                    tag     = 'Coarse-1_XV_300'
                    trange  = [3,11]



    [fit.Coarse-Phys]
        [fit.Coarse-Phys.xfstpar]
            smlist = ['1S']
            [fit.Coarse-Phys.xfstpar.mom]
                [fit.Coarse-Phys.xfstpar.mom.100]
                    nstates = 2
                    tag     = 'Coarse-Phys_xfstpar_100'
                    trange  = [3,11]
                [fit.Coarse-Phys.xfstpar.mom.200]
                    nstates = 2
                    tag     = 'Coarse-Phys_xfstpar_200'
                    trange  = [3,11]            
                [fit.Coarse-Phys.xfstpar.mom.300]
                    nstates = 2
                    tag     = 'Coarse-Phys_xfstpar_300'
                    trange  = [3,11]

        [fit.Coarse-Phys.RA1]
            smlist = ['1S']
            [fit.Coarse-Phys.RA1.mom]
                [fit.Coarse-Phys.RA1.mom.000]
                    nstates = 2
                    tag     = 'Coarse-Phys_RA1_000'
                    trange  = [3,11]
                [fit.Coarse-Phys.RA1.mom.100]
                    nstates = 2
                    tag     = 'Coarse-Phys_RA1_100'
                    trange  = [3,11]
                [fit.Coarse-Phys.RA1.mom.200]
                    nstates = 2
                    tag     = 'Coarse-Phys_RA1_200'
                    trange  = [3,11]            
                [fit.Coarse-Phys.RA1.mom.300]
                    nstates = 2
                    tag     = 'Coarse-Phys_RA1_300'
                    trange  = [3,11]

        [fit.Coarse-Phys.ZRA1]
            smlist = ['1S']
            [fit.Coarse-Phys.ZRA1.mom]
                [fit.Coarse-Phys.ZRA1.mom.000]
                    nstates = 2
                    tag     = 'Coarse-Phys_ZRA1_000'
                    trange  = [3,11]

        [fit.Coarse-Phys.R0]
            smlist = ['1S']
            [fit.Coarse-Phys.R0.mom]
                [fit.Coarse-Phys.R0.mom.100]
                    nstates = 2
                    tag     = 'Coarse-Phys_R0_100'
                    trange  = [3,11]
                [fit.Coarse-Phys.R0.mom.200]
                    nstates = 2
                    tag     = 'Coarse-Phys_R0_200'
                    trange  = [3,11]            
                [fit.Coarse-Phys.R0.mom.300]
                    nstates = 2
                    tag     = 'Coarse-Phys_R0_300'
                    trange  = [3,11]

        [fit.Coarse-Phys.R1]
            smlist = ['1S']
            [fit.Coarse-Phys.R1.mom]
                [fit.Coarse-Phys.R1.mom.100]
                    nstates = 2
                    tag     = 'Coarse-Phys_R1_100'
                    trange  = [3,11]
                [fit.Coarse-Phys.R1.mom.200]
                    nstates = 2
                    tag     = 'Coarse-Phys_R1_200'
                    trange  = [3,11]            
                [fit.Coarse-Phys.R1.mom.300]
                    nstates = 2
                    tag     = 'Coarse-Phys_R1_300'
                    trange  = [3,11]

        [fit.Coarse-Phys.XV]
            smlist = ['1S']
            [fit.Coarse-Phys.XV.mom]
                [fit.Coarse-Phys.XV.mom.100]
                    nstates = 2
                    tag     = 'Coarse-Phys_XV_100'
                    trange  = [3,11]
                [fit.Coarse-Phys.XV.mom.200]
                    nstates = 2
                    tag     = 'Coarse-Phys_XV_200'
                    trange  = [3,11]            
                [fit.Coarse-Phys.XV.mom.300]
                    nstates = 2
                    tag     = 'Coarse-Phys_XV_300'
                    trange  = [3,11]




    [fit.Fine-1]
        [fit.Fine-1.xfstpar]
            smlist = ['1S']
            [fit.Fine-1.xfstpar.mom]
                [fit.Fine-1.xfstpar.mom.100]
                    nstates = 2
                    tag     = 'Fine-1_xfstpar_100'
                    trange  = [3,14]
                [fit.Fine-1.xfstpar.mom.200]
                    nstates = 2
                    tag     = 'Fine-1_xfstpar_200'
                    trange  = [3,14]            
                [fit.Fine-1.xfstpar.mom.300]
                    nstates = 2
                    tag     = 'Fine-1_xfstpar_300'
                    trange  = [3,14]

        [fit.Fine-1.RA1]
            smlist = ['1S']
            [fit.Fine-1.RA1.mom]
                [fit.Fine-1.RA1.mom.000]
                    nstates = 2
                    tag     = 'Fine-1_RA1_000'
                    trange  = [3,14]
                [fit.Fine-1.RA1.mom.100]
                    nstates = 2
                    tag     = 'Fine-1_RA1_100'
                    trange  = [3,14]
                [fit.Fine-1.RA1.mom.200]
                    nstates = 2
                    tag     = 'Fine-1_RA1_200'
                    trange  = [3,14]            
                [fit.Fine-1.RA1.mom.300]
                    nstates = 2
                    tag     = 'Fine-1_RA1_300'
                    trange  = [3,14]

        [fit.Fine-1.ZRA1]
            smlist = ['1S']
            [fit.Fine-1.ZRA1.mom]
                [fit.Fine-1.ZRA1.mom.000]
                    nstates = 2
                    tag     = 'Fine-1_ZRA1_000'
                    trange  = [3,14]

        [fit.Fine-1.R0]
            smlist = ['1S']
            [fit.Fine-1.R0.mom]
                [fit.Fine-1.R0.mom.100]
                    nstates = 2
                    tag     = 'Fine-1_R0_100'
                    trange  = [3,14]
                [fit.Fine-1.R0.mom.200]
                    nstates = 2
                    tag     = 'Fine-1_R0_200'
                    trange  = [3,14]            
                [fit.Fine-1.R0.mom.300]
                    nstates = 2
                    tag     = 'Fine-1_R0_300'
                    trange  = [3,14]

        [fit.Fine-1.R1]
            smlist = ['1S']
            [fit.Fine-1.R1.mom]
                [fit.Fine-1.R1.mom.100]
                    nstates = 2
                    tag     = 'Fine-1_R1_100'
                    trange  = [3,14]
                [fit.Fine-1.R1.mom.200]
                    nstates = 2
                    tag     = 'Fine-1_R1_200'
                    trange  = [3,14]            
                [fit.Fine-1.R1.mom.300]
                    nstates = 2
                    tag     = 'Fine-1_R1_300'
                    trange  = [3,14]

        [fit.Fine-1.XV]
            smlist = ['1S']
            [fit.Fine-1.XV.mom]
                [fit.Fine-1.XV.mom.100]
                    nstates = 2
                    tag     = 'Fine-1_XV_100'
                    trange  = [3,14]
                [fit.Fine-1.XV.mom.200]
                    nstates = 2
                    tag     = 'Fine-1_XV_200'
                    trange  = [3,14]            
                [fit.Fine-1.XV.mom.300]
                    nstates = 2
                    tag     = 'Fine-1_XV_300'
                    trange  = [3,14]

