# Configs
author = 'pietro.butti'
title = '2pts fits'

# Meson list
[ensemble]
    list = ['MediumCoarse','Coarse-2','Coarse-1','Coarse-Phys','Fine-1','Fine-Phys','SuperFine']

[meson]
    list = ['Dst']

[momenta]
    list = ['000','100','200','300','400','110','211','222']






[data]
    mdata = '/Users/pietro/code/software/B2heavy/b2heavy/FnalHISQMetadata.py'

    [data.MediumCoarse]
        name     = 'MediumCoarse'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 13
        mom_list = ['000','100','200','300','400','110','211','222']
        Nt       = 48

    [data.Coarse-1]
        name     = 'Coarse-1'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 11
        mom_list = ['000','100','200','300','110','211']
        Nt       = 64

    [data.Coarse-2]
        name     = 'Coarse-2'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 16
        mom_list = ['000','100','200','300','110','211']
        Nt       = 64
    
    [data.Coarse-Phys]
        name     = 'Coarse-Phys'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 19
        mom_list = ['000','100','200','300','400','110','211','222']
        Nt       = 64
    
    [data.Fine-1]
        name     = 'Fine-1'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 16
        mom_list = ['000','100','200','300','400','110','211','222']
        Nt       = 96
    
    [data.Fine-Phys]
        name     = 'Fine-Phys'
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize  = 16
        mom_list = ['000','100','200','300','400','110','211','222']
        Nt       = 96
    
    [data.SuperFine]
        name = "SuperFine"
        data_dir = "/Users/pietro/code/data_analysis/BtoD/Alex"
        binsize = 22
        mom_list = [ "000", "100", "200", "300", "400", "110", "211", "222",]
        Nt = 192



[fit.MediumCoarse.Dst]
    smlist = [ "d-d", "1S-1S", "d-1S",]

[fit.Coarse-2.Dst]
    smlist = [ "d-d", "1S-1S", "d-1S",]

[fit.Coarse-1.Dst]
    smlist = [ "d-d", "1S-1S", "d-1S",]

[fit.Coarse-Phys.Dst]
    smlist = [ "d-d", "1S-1S", "d-1S",]

[fit.Fine-1.Dst]
    smlist = [ "d-d", "1S-1S", "d-1S",]

[fit.Fine-Phys.Dst]
    smlist = [ "d-d", "1S-1S", "d-1S",]

[fit.SuperFine.Dst]
    smlist = [ "d-d", "1S-1S", "d-1S",]




[fit.MediumCoarse.Dst.mom.000]
tag = "MediumCoarse_Dst_000"
nstates = 3
trange_eff = [ 10, 21,]
trange = [ 4, 21,]
svd = 1e-12

[fit.MediumCoarse.Dst.mom.100]
tag = "MediumCoarse_Dst_100"
nstates = 3
trange_eff = [ 10, 21,]
trange = [ 4, 21,]
svd = 1e-12

[fit.MediumCoarse.Dst.mom.200]
tag = "MediumCoarse_Dst_200"
nstates = 3
trange_eff = [ 10, 20,]
trange = [ 4, 20,]
svd = 1e-12

[fit.MediumCoarse.Dst.mom.300]
tag = "MediumCoarse_Dst_300"
nstates = 3
trange_eff = [ 10, 18,]
trange = [ 4, 18,]
svd = 1e-12

[fit.MediumCoarse.Dst.mom.400]
tag = "MediumCoarse_Dst_400"
nstates = 3
trange_eff = [ 10, 15,]
trange = [ 4, 15,]
svd = 1e-12

[fit.MediumCoarse.Dst.mom.110]
tag = "MediumCoarse_Dst_110"
nstates = 3
trange_eff = [ 10, 21,]
trange = [ 4, 21,]
svd = 1e-12

[fit.MediumCoarse.Dst.mom.211]
tag = "MediumCoarse_Dst_211"
nstates = 3
trange_eff = [ 10, 20,]
trange = [ 4, 20,]
svd = 1e-12

[fit.MediumCoarse.Dst.mom.222]
tag = "MediumCoarse_Dst_222"
nstates = 3
trange_eff = [ 10, 16,]
trange = [ 4, 16,]
svd = 1e-12

[fit.Coarse-2.Dst.mom.000]
tag = "Coarse-2_Dst_000"
nstates = 3
trange_eff = [ 12, 27,]
trange = [ 5, 27,]
svd = 1e-12

[fit.Coarse-2.Dst.mom.100]
tag = "Coarse-2_Dst_100"
nstates = 3
trange_eff = [ 12, 25,]
trange = [ 5, 25,]
svd = 1e-12

[fit.Coarse-2.Dst.mom.200]
tag = "Coarse-2_Dst_200"
nstates = 3
trange_eff = [ 12, 20,]
trange = [ 5, 20,]
svd = 1e-12

[fit.Coarse-2.Dst.mom.300]
tag = "Coarse-2_Dst_300"
nstates = 3
trange_eff = [ 12, 18,]
trange = [ 5, 18,]
svd = 1e-12

[fit.Coarse-2.Dst.mom.400]

[fit.Coarse-2.Dst.mom.110]
tag = "Coarse-2_Dst_110"
nstates = 3
trange_eff = [ 12, 22,]
trange = [ 5, 22,]
svd = 1e-12

[fit.Coarse-2.Dst.mom.211]
tag = "Coarse-2_Dst_211"
nstates = 3
trange_eff = [ 12, 18,]
trange = [ 5, 18,]
svd = 1e-12

[fit.Coarse-2.Dst.mom.222]

[fit.Coarse-1.Dst.mom.000]
tag = "Coarse-1_Dst_000"
nstates = 3
trange_eff = [ 12, 28,]
trange = [ 5, 28,]
svd = 1e-12

[fit.Coarse-1.Dst.mom.100]
tag = "Coarse-1_Dst_100"
nstates = 3
trange_eff = [ 12, 26,]
trange = [ 5, 26,]
svd = 1e-12

[fit.Coarse-1.Dst.mom.200]
tag = "Coarse-1_Dst_200"
nstates = 3
trange_eff = [ 12, 22,]
trange = [ 5, 22,]
svd = 1e-12

[fit.Coarse-1.Dst.mom.300]
tag = "Coarse-1_Dst_300"
nstates = 3
trange_eff = [ 12, 20,]
trange = [ 5, 20,]
svd = 1e-12

[fit.Coarse-1.Dst.mom.400]

[fit.Coarse-1.Dst.mom.110]
tag = "Coarse-1_Dst_110"
nstates = 3
trange_eff = [ 12, 26,]
trange = [ 5, 26,]
svd = 1e-12

[fit.Coarse-1.Dst.mom.211]
tag = "Coarse-1_Dst_211"
nstates = 3
trange_eff = [ 12, 21,]
trange = [ 5, 21,]
svd = 1e-12

[fit.Coarse-1.Dst.mom.222]

[fit.Coarse-Phys.Dst.mom.000]
tag = "Coarse-Phys_Dst_000"
nstates = 3
trange_eff = [ 12, 26,]
trange = [ 5, 26,]
svd = 1e-12

[fit.Coarse-Phys.Dst.mom.100]
tag = "Coarse-Phys_Dst_100"
nstates = 3
trange_eff = [ 12, 25,]
trange = [ 5, 25,]
svd = 1e-12

[fit.Coarse-Phys.Dst.mom.200]
tag = "Coarse-Phys_Dst_200"
nstates = 3
trange_eff = [ 12, 24,]
trange = [ 5, 24,]
svd = 1e-12

[fit.Coarse-Phys.Dst.mom.300]
tag = "Coarse-Phys_Dst_300"
nstates = 3
trange_eff = [ 12, 21,]
trange = [ 5, 21,]
svd = 1e-12

[fit.Coarse-Phys.Dst.mom.400]
tag = "Coarse-Phys_Dst_400"
nstates = 3
trange_eff = [ 12, 21,]
trange = [ 5, 21,]
svd = 1e-12

[fit.Coarse-Phys.Dst.mom.110]
tag = "Coarse-Phys_Dst_110"
nstates = 3
trange_eff = [ 12, 24,]
trange = [ 5, 24,]
svd = 1e-12

[fit.Coarse-Phys.Dst.mom.211]
tag = "Coarse-Phys_Dst_211"
nstates = 3
trange_eff = [ 12, 23,]
trange = [ 5, 23,]
svd = 1e-12

[fit.Coarse-Phys.Dst.mom.222]
tag = "Coarse-Phys_Dst_222"
nstates = 3
trange_eff = [ 12, 21,]
trange = [ 5, 21,]
svd = 1e-12

[fit.Fine-1.Dst.mom.000]
tag = "Fine-1_Dst_000"
nstates = 3
trange_eff = [ 16, 36,]
trange = [ 7, 36,]
svd = 1e-12

[fit.Fine-1.Dst.mom.100]
tag = "Fine-1_Dst_100"
nstates = 3
trange_eff = [ 16, 36,]
trange = [ 7, 36,]
svd = 1e-12

[fit.Fine-1.Dst.mom.200]
tag = "Fine-1_Dst_200"
nstates = 3
trange_eff = [ 16, 32,]
trange = [ 7, 32,]
svd = 1e-12

[fit.Fine-1.Dst.mom.300]
tag = "Fine-1_Dst_300"
nstates = 3
trange_eff = [ 16, 31,]
trange = [ 7, 31,]
svd = 1e-12

[fit.Fine-1.Dst.mom.400]
tag = "Fine-1_Dst_400"
nstates = 3
trange_eff = [ 16, 24,]
trange = [ 7, 24,]
svd = 1e-12

[fit.Fine-1.Dst.mom.110]
tag = "Fine-1_Dst_110"
nstates = 3
trange_eff = [ 16, 34,]
trange = [ 7, 34,]
svd = 1e-12

[fit.Fine-1.Dst.mom.211]
tag = "Fine-1_Dst_211"
nstates = 3
trange_eff = [ 16, 31,]
trange = [ 7, 31,]
svd = 1e-12

[fit.Fine-1.Dst.mom.222]
tag = "Fine-1_Dst_222"
nstates = 3
trange_eff = [ 16, 26,]
trange = [ 7, 26,]
svd = 1e-12

[fit.Fine-Phys.Dst.mom.000]
tag = "Fine-Phys_Dst_000"
nstates = 3
trange_eff = [ 17, 38,]
trange = [ 7, 38,]
svd = 1e-12

[fit.Fine-Phys.Dst.mom.100]
tag = "Fine-Phys_Dst_100"
nstates = 3
trange_eff = [ 17, 36,]
trange = [ 7, 36,]
svd = 1e-12

[fit.Fine-Phys.Dst.mom.200]
tag = "Fine-Phys_Dst_200"
nstates = 3
trange_eff = [ 17, 32,]
trange = [ 7, 32,]
svd = 1e-12

[fit.Fine-Phys.Dst.mom.300]
tag = "Fine-Phys_Dst_300"
nstates = 3
trange_eff = [ 17, 30,]
trange = [ 7, 30,]
svd = 1e-12

[fit.Fine-Phys.Dst.mom.400]
tag = "Fine-Phys_Dst_400"
nstates = 3
trange_eff = [ 17, 28,]
trange = [ 7, 28,]
svd = 1e-12

[fit.Fine-Phys.Dst.mom.110]
tag = "Fine-Phys_Dst_110"
nstates = 3
trange_eff = [ 17, 36,]
trange = [ 7, 36,]
svd = 1e-12

[fit.Fine-Phys.Dst.mom.211]
tag = "Fine-Phys_Dst_211"
nstates = 3
trange_eff = [ 17, 32,]
trange = [ 7, 32,]
svd = 1e-12

[fit.Fine-Phys.Dst.mom.222]
tag = "Fine-Phys_Dst_222"
nstates = 3
trange_eff = [ 17, 31,]
trange = [ 7, 31,]
svd = 1e-12

[fit.SuperFine.Dst.mom.000]
tag = "SuperFine_Dst_000"
nstates = 3
trange_eff = [ 26, 55,]
trange = [ 11, 55,]
svd = 1e-12

[fit.SuperFine.Dst.mom.100]
tag = "SuperFine_Dst_100"
nstates = 3
trange_eff = [ 26, 57,]
trange = [ 11, 57,]
svd = 1e-12

[fit.SuperFine.Dst.mom.200]
tag = "SuperFine_Dst_200"
nstates = 3
trange_eff = [ 26, 53,]
trange = [ 11, 53,]
svd = 1e-12

[fit.SuperFine.Dst.mom.300]
tag = "SuperFine_Dst_300"
nstates = 3
trange_eff = [ 26, 43,]
trange = [ 11, 43,]
svd = 1e-12

[fit.SuperFine.Dst.mom.400]
tag = "SuperFine_Dst_400"
nstates = 3
trange_eff = [ 26, 42,]
trange = [ 11, 42,]
svd = 1e-12

[fit.SuperFine.Dst.mom.110]
tag = "SuperFine_Dst_110"
nstates = 3
trange_eff = [ 26, 53,]
trange = [ 11, 53,]
svd = 1e-12

[fit.SuperFine.Dst.mom.211]
tag = "SuperFine_Dst_211"
nstates = 3
trange_eff = [ 26, 46,]
trange = [ 11, 46,]
svd = 1e-12

[fit.SuperFine.Dst.mom.222]
tag = "SuperFine_Dst_222"
nstates = 3
trange_eff = [ 26, 42,]
trange = [ 11, 42,]
svd = 1e-12
